name: Go CI/CD Pipeline

# It works automatically with any Push or Pull Request
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Pull the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Setting up the Go language
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26'

    # 3. Download libraries
    - name: Install Dependencies
      run: go mod download

    # 4. Run all unit tests(Unit Tests)
    - name: Run Unit Tests
      run: go test -v ./...

    # 5. Ensure that the server is buildable (Build)
    - name: Build Project
      run: go build -v ./main.go
